version: '2'
services:
  app:
    build: ./server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      WEBPORT: 8000
   
  postgres:
    build: ./db
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}